---
editor: 
  markdown: 
    wrap: sentence
---

# Task Analysis {.appendix}

Here are some questions to guide you through the process of doing a task analysis.
You don't have to specifically answer each one of these (and some may not apply), but they should get you started thinking in the right direction.

What are the prerequisites, for both knowledge and e.g. software setup?

What are the basic requirements for any data that the method is used on?
- Are missing values allowed?
- Should the data be confined within a certain range?
- Does the data have to be approximately normally distributed?

What are the basic components of the task?
- Outline these in a bit more detail

What decisions does the user need to be prepared to make on the fly?

What questions should the user ask of the "first draft" of the product?
What adjustments may need to be made?

## Additional Guidance

Your check-in should answer these basic questions (and similar concerns that apply more directly to your topic).

Once you've completed the check-in, you can use this section to jump-start an introduction/set-up/getting started section in your user guide.
This document should remain as an appendix to your main report.

------------------------------------------------------------------------

***Pre-Requisite Knowledge Required***

Before addressing the matter of sensitive questions, it is assumed that:

1.  There is an existing survey template/outline being used (Online Survey (Google Forms/Microsoft Forms) or Physical Survey Design).

2.  There is a clear set of underlying question(s) that the survey is aiming to address.

3.   The audience/target population of the survey is known and clearly defined.

Because sensitivity is a subjective classification that depends on the population of interest, it is impossible to address the issues that arise from sensitivity without understanding the context the survey is being created for.
It is also important to understand that it is impossible to 100% remove the effect of non-response and misreporting biases, and that's okay.

***Steps Outline***

**Pre-Data Collection Requirements**

-   Surveyors need to do some preliminary research on their target population and examine its underlying characteristics. Are there any commonalities such as ethnicity, religion, political beliefs, historical or current events, or traditions that are uniquely more prevalent in this population?
-   What format(s) can the survey be issued in? Does it need to be done In-Person? Can it be done asynchronously online? Is there a need for observers? To minimize the effects of non-response and misreporting biases, researchers recommend an asynchronous approach.
-   What is being done to ensure the confidentiality and/or anonymity of responses? The effects of both bias types are much higher in cases where respondents are aware of or believe that their responses are neither confidential nor anonymous. If these are impossible to ensure (or do at all), make sure the participants are aware ahead of time to maintain a positive relationship between surveyor and respondent.
-   Determine whether or not the sensitive question needs to be included at all. If it's possible to collect the information needed without asking any sensitive questions, *remove the question*.
-   Have a clear and rigid privacy policy in place. Make sure that this policy is being followed at all times throughout the entire data collection and storing process.

**Confidentiality, Anonymity, and Privacy**

**Data Collection Requirements**

-   For Asynchronous Surveys that ensure confidentiality AND anonymity, most of this step can be ignored.
    -   In almost all non-asynchronous surveys, anonymity is lost.
    -   To reduce the effect of bias, there are a few strategies that can be deployed to ensure more honest responses, including:

```         
 1) Randomized Response Technique (RRT) (Note all of these will be defined in the actual user guide, this is just an outline)
 2) Item Count Technique
 3) Bogus Pipeline Technique
 4) Priming
 
```

-   It is recommended to include sensitive questions towards the middle of a survey, if possible. Including them too early runs the risk of encouraging a higher rate of non-response throughout the rest of the survey, and including them at the end of the survey can lead to a sense of distrust between the respondent and the survey.
-   Question phrasing is one of the most important factors that determine the way respondents choose to answer a question. If possible, try to make the question open-ended when discussing sensitive topics to promote honest responses. For questions that require a specific number (like income, amount of times an activity has occurred), it is very difficult to get exact answers that are reflective of a respondent's real world behaviors. Instead, provide ranges of values as options (0 times, 1-2 times, 3-4, times 5+).
-   If a respondent does not want to answer a question at all, allow them to provide a "N/A" or "I prefer not to say" response. Make sure that the N/A option has a neutral tone, as opposed to "Respondent will not participate" or "Respondent is choosing not to respond". Do not put the blame on the non-response on the respondent, as that will only damage the relationship. While non-response is detrimental to the results of the survey, damaging the surveyor/respondent relationship will result in an even worse outcome. Additionally, as an inverse relationship exists between non-response and misreporting biases, preventing respondents from providing a N/A option will most likely result in an increase in misreporting.

**On-the-Fly Issues**

-   During the data-collection process, if a respondent ever requests to know why a sensitive question is being included, always tell the truth.
    Honesty is the best policy, and the most important thing when it comes to sensitive questions is to maintain a trustworthy relationship with respondents.
    Make clear what the privacy policy is when collecting data to ensure that their information is being protected.

-   If a respondent has multiple instances of non-response, take note of their non-response separately and include that fact in the results.
    Do not single out those who had multiple instances of non-response.

-   Always be open to take in constructive respondent feedback.
    The target audience is the best group equipped to understand how they feel about sensitive issues, so if they provide feedback that can improve the accuracy of the results, always be willing to listen.

**Measuring Results**

-   Response Rate Percentage (RRP).
    The higher, the better.

-   Examine a Sample of Responses.
    For open-ended questions, do the answers reflect the question being asked, or was it clear that there is a degree of dishonesty in the results.
    For range-questions, examine the plots of the histogram.
    Do the plots make rational sense based on the type of question being asked?
    For example, income-based questions should typically have a skewed distribution.
